### PR TITLE
meta-balena-up-board: use grub recipes from meta-balena

### PR DESCRIPTION
**Pull request by klutchell**
Use grub recipes from meta-balena, which are based on poky.

Change-type: minor
Depends-on: balena-os/meta-balena#2085
Signed-off-by: Kyle Harding <kyle@balena.io>

### CODE REVIEW

**Comment by klutchell** [comment]
@resin-jenkins add to whitelist

**Comment by klutchell** [comment]
@resin-jenkins ok to test

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by klutchell** [comment]
@resin-jenkins add to whitelist

**Comment by jakogut** [comment]
@klutchell This boots for me in a VM.

**Review by jakogut — APPROVED** [review]
LGTM

**Comment by acostach** [comment]
@resin-jenkins test this please

**Pull request merged**
