### PR TITLE
up-board.coffee: Updating links to getting started guide

### PR DESCRIPTION
**Pull request by garethtdavies**
Changelog-entry: Update links to getting started guide from resin.io to balena.io
Signed-off-by: Gareth Davies <gareth@balena.io>

### CODE REVIEW

**Comment by acostach** [comment]
@resin-jenkins test this please
@balena-ci retest this please

**Comment by floion** [comment]
@balena-ci retest

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins ok to test

**Pull request merged**
